package ${package}<#if moduleName??>.${moduleName}</#if>.entity<#if subModuleName??>.${subModuleName}</#if>;

import com.dcjet.edi.core.base.model.AbstractReceiveParam;
import com.dcjet.edi.ftp.annotation.ColumnFiled;
import com.dcjet.edi.util.TimestampFormatter;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.xdo.validation.annotation.XdoSize;
import lombok.Getter;
import lombok.Setter;
import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.Column;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Digits;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.math.BigDecimal;
import java.util.Date;
/**
* generated by Generate 神码
*
*
* @author xdoV2.0
* @date: 2021-8-31
*/
@Setter
@Getter
@Table(name = "${tableName}")
public class ${ClassName}<#if baseClassEntity??> extends ${baseClassEntity.code}</#if> {

    @Override
    public String generateBizId() {
      return null;
    }

    @Override
    public String specificCheck() {
      return null;
    }

    @Override
    public void generateDefaultField() {

    }

    /**
    * 错误信息
    */
    @Transient
    private String errorMsg;

    public String getErrorMsg() {
    return this.errorInfo;
    }


<#list columnList as column>
    <#if (baseClassEntity?? && baseClassEntity.fields?split(",")?seq_contains(column.attrName))
    || "errorMsg"?split(",")?seq_contains(column.attrName)>
    <#else>

        <#if column.columnComment!?length gt 0>
          /**
          * ${column.columnComment}
          */
        </#if>
        <#if column.required>
            <#if "String,BigDecimal"?split(",")?seq_contains(column.attrType)>
              @NotEmpty(message = "<#if column.columnComment!?length gt 0>${column.columnComment}<#else>${column.attrName}</#if>不能为空！")
            </#if>
            <#if "Date"?split(",")?seq_contains(column.attrType)>
              @NotNull(message = "<#if column.columnComment!?length gt 0>${column.columnComment}<#else>${column.attrName}</#if>不能为空！")
            </#if>
        </#if>
        <#if column.attrType == 'String' && (column.characterMaximumLength!?length gt 0)>
          @XdoSize(max = ${column.characterMaximumLength}, message = "<#if column.columnComment!?length gt 0>${column.columnComment}<#else>${column.attrName}</#if>长度不能超过${column.characterMaximumLength}位字节长度(一个汉字2位字节长度)!")
        </#if>
        <#if column.attrType == 'BigDecimal' && (column.numericPrecision!?length gt 0) && (column.numericScale!?length gt 0)>
          @Digits(integer = ${column.numericPrecision}, fraction = ${column.numericScale}, message = "<#if column.columnComment!?length gt 0>${column.columnComment}<#else>${column.attrName}</#if>必须为数字,整数位最大${column.numericPrecision}位,小数最大${column.numericScale}位!")
        </#if>
        <#if column.attrType == 'Date'>
          @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
          @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
        </#if>
      @Column(name = "${column.columnName}")
      @ColumnFiled(name = "<#if column.columnComment!?length gt 0>${column.columnComment}<#else>${column.attrName}</#if>")
      private ${column.attrType} ${column.attrName};
    </#if>
</#list>

}