package ${package}<#if moduleName??>.${moduleName}</#if>.entity<#if subModuleName??>.${subModuleName}</#if>;

import com.dcjet.edi.core.base.model.AbstractReceiveParam;
import com.dcjet.edi.ftp.annotation.ColumnFiled;
import com.dcjet.edi.util.TimestampFormatter;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.xdo.validation.annotation.XdoSize;
import lombok.Getter;
import lombok.Setter;
import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.Column;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Digits;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.math.BigDecimal;
import java.util.Date;
/**
* generated by Generate 神码
*
*
* @author xdoV2.0
* @date: 2021-8-31
*/
@Setter
@Getter
@Table(name = "${tableName}")
public class ${ClassName}<#if baseClassEntity??> extends ${baseClassEntity.code}</#if> {

@Override
public String generateBizId() {
return null;
}

@Override
public String specificCheck() {
return null;
}

@Override
public void generateDefaultField() {

}

/**
* 错误信息
*/
@Transient
private String errorMsg;

public String getErrorMsg() {
return this.errorInfo;
}


<#list columnList as filed>
    <#if (baseClassEntity?? && baseClassEntity.fields?split(",")?seq_contains(filed.attrName))
    || "errorMsg"?split(",")?seq_contains(filed.attrName)>
    <#else>

        <#if filed.columnComment!?length gt 0>
          /**
          * ${filed.columnComment}
          */
        </#if>
        <#if filed.required>
            <#if "String,BigDecimal"?split(",")?seq_contains(filed.attrType)>
              @NotEmpty(message = "<#if filed.columnComment!?length gt 0>${filed.columnComment}<#else>${filed.attrName}</#if>不能为空！")
            </#if>
            <#if "Date"?split(",")?seq_contains(filed.attrType)>
              @NotNull(message = "<#if filed.columnComment!?length gt 0>${filed.columnComment}<#else>${filed.attrName}</#if>不能为空！")
            </#if>
        </#if>
        <#if filed.attrType == 'String' && (filed.characterMaximumLength!?length gt 0)>
          @XdoSize(max = ${filed.characterMaximumLength}, message = "<#if filed.columnComment!?length gt 0>${filed.columnComment}<#else>${filed.attrName}</#if>长度不能超过${filed.characterMaximumLength}位字节长度(一个汉字2位字节长度)!")
        </#if>
        <#if filed.attrType == 'BigDecimal' && (filed.numericPrecision!?length gt 0) && (filed.numericScale!?length gt 0)>
          @Digits(integer = ${filed.numericPrecision}, fraction = ${filed.numericScale}, message = "<#if filed.columnComment!?length gt 0>${filed.columnComment}<#else>${filed.attrName}</#if>必须为数字,整数位最大${filed.numericPrecision}位,小数最大${filed.numericScale}位!")
        </#if>
        <#if filed.attrType == 'Date'>
          @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
          @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
        </#if>
      @Column(name = "${filed.columnName}")
      @ColumnFiled(name = "<#if filed.columnComment!?length gt 0>${filed.columnComment}<#else>${filed.attrName}</#if>")
        <#if filed.paramNameList??&&(filed.paramNameList?size>0)>
            <#list filed.paramNameList as value>
            </#list>
          @JsonAlias({<#list filed.paramNameList as value>"${value}"<#if value_index != (filed.paramNameList?size-1)>,</#if></#list>})
        </#if>
      private ${filed.attrType} ${filed.attrName};
    </#if>
</#list>

}